### ISSUE TITLE
Addon not working in recent builds.

### ISSUE THREAD

**Issue by cyberlecs** [JuhaW/Vray-Delete-unused-materials-and-nodetrees#1]
Hi JuhaW,

The script is not working in the last Vray/Blender builds of nightlies (a378f2b 2018-12-02).
This is the error message in the console:

> Exception in module register(): C:\Users\Leandro\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Vray-Delete-unused-materials-and-nodetrees-master\__init__.py
> Traceback (most recent call last):
>   File "C:\Users\Leandro\Desktop\VB\2.79\scripts\modules\addon_utils.py", line 370, in enable
>     mod.register()
>   File "C:\Users\Leandro\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Vray-Delete-unused-materials-and-nodetrees-master\__init__.py", line 126, in register
>     bpy.types.VRayPanelNodeTrees.append(Vray_Materials_Delete)
> AttributeError: 'RNA_Types' object has no attribute 'VRayPanelNodeTrees'

In older builds (9134bcc 2018-10-26) is working fine.

Regards,
Leandro.

**Comment by JuhaW** [comment]
Yes, a few panel names has changed. Fixed.

**Comment by cyberlecs** [comment]
Thanks!
